---
title: "Plots"
author: "Owen Fiore"
date: "2022-12-09"
output: html_document
---

```{r}
times <- read.csv("../Data/PaperData.csv")
View(times)
colnames(times) <- c("Year", "Type", "Time", "RxnTime", "Gender", "Batch")
```

#DataSets
```{r}
men_finals <- subset(times, Type == "F" & Gender == "M" & Time != 'DQ') # & Year < 2022)
women_finals <- subset(times, Type == "F" & Gender == "F" & Time != 'DQ')

men_pooled <- subset(times, (Type == "F" | Type == "S") & Gender == "M" & Time != 'DQ')
women_pooled <- subset(times, (Type == "F" | Type == "S") & Gender == "F" & Time != 'DQ')
```

#Models
```{r}
library(lme4)
finals.lme <- lmer(RxnTime ~ (1|Year), data = men_pooled)
```

###Functions
```{r}
simfit <- function(fit2, n = 12000000) {
  vc <- as.data.frame(VarCorr(fit2))
  ## mu <- exp(coef(fit2)$Year[,]) ## using fitted random effects only
  z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
  mu <- exp(fixef(fit2) + z)
  shape <- 1 / vc$vcov[2]
  x <- rgamma(n, shape = shape, scale = mu / shape)
  x
}

x <- simfit(fit2)
mean(x < 0.1)
quantile(x, prob = c(.00001, .0001, .0005, .001))
## compare with and without random effect
plot(density(x)) # with random effect
curve(dgamma(x, shape = 1 / sfit0$dispersion,
             scale = exp(coef(fit0)) * sfit0$dispersion),
      0.08, 0.22, add = TRUE, col = "blue") # fixed effect only
```

#Figures
```{r}
pdf(file = "TBY.pdf")
plot(aggregate(men_pooled$RxnTime, list(men_pooled$Year), FUN = mean), xlab = "Year", ylab = "Reaction time in seconds", main = "Mean Reaction Time By Year")
dev.off()
```

```{r}
pdf(file = "Skew.pdf")
hist(resid(finals.lme), xlab = "Residuals of Linear mixed effects model", main = "Right skew when plotting the residuals of the linear mixed effects model")
dev.off()
```
```{r}
pdf(file = "Gamma_skew.pdf")
dev.off()
```

```{r}
pdf(file = "DataBoxplot.pdf")
boxplot(RxnTime ~ Year, data = men_pooled, xlab = "Year", ylab = "Reaction Time in seconds", main = "Men's Semifinal and Final Reaction Time Boxplot Data")
dev.off()
```

```{r}
pdf(file = "DataScatterplot.pdf")
plot(RxnTime ~ Year, data = men_pooled, xlab = "Year", ylab = "Reaction Time in seconds", main = "Men's Semifinal and Final Reaction Time Scatterplot Data")
dev.off()
```

```{r}
set.seed(1)
library(lme4)
pdf(file = "Men_Density_Year.pdf")
fit2 <- glmer(RxnTime ~ (1 | Year), data = men_pooled, family = Gamma(link = "log"))
fit0 <- glm(RxnTime ~ 1, data = men_pooled, family = Gamma(link = "log"))
sfit0 <- summary(fit0)
simfit <- function(fit2, n = 12000000) {
  vc <- as.data.frame(VarCorr(fit2))
  ## mu <- exp(coef(fit2)$Year[,]) ## using fitted random effects only
  z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
  mu <- exp(fixef(fit2) + z)
  shape <- 1 / vc$vcov[2]
  x <- rgamma(n, shape = shape, scale = mu / shape)
  x
}

x <- simfit(fit2)
mean(x < 0.1)
quantile(x, prob = c(.00001, .0001, .0005, .001))
## compare with and without random effect
plot(density(x), main = "Men's Pooled With Only Year Effect") # with random effect
curve(dgamma(x, shape = 1 / sfit0$dispersion,
             scale = exp(coef(fit0)) * sfit0$dispersion),
      0.08, 0.22, add = TRUE, col = "blue") # fixed effect only
legend("right", title = "Probability mean less than", legend = " 0.1 is 0.006847")
dev.off()
```


```{r}
set.seed(1)
library(lme4)
pdf(file = "Men_Density_Batch.pdf")
fit2 <- glmer(RxnTime ~ (1 | Batch), data = men_pooled, family = Gamma(link = "log"))
fit0 <- glm(RxnTime ~ 1, data = men_pooled, family = Gamma(link = "log"))
sfit0 <- summary(fit0)
simfit <- function(fit2, n = 12000000) {
  vc <- as.data.frame(VarCorr(fit2))
  ## mu <- exp(coef(fit2)$Year[,]) ## using fitted random effects only
  z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
  mu <- exp(fixef(fit2) + z)
  shape <- 1 / vc$vcov[2]
  x <- rgamma(n, shape = shape, scale = mu / shape)
  x
}

x <- simfit(fit2)
mean(x < 0.1)
quantile(x, prob = c(.00001, .0001, .0005, .001))
## compare with and without random effect
plot(density(x), main = "Men's Pooled With Only Batch Effect") # with random effect
curve(dgamma(x, shape = 1 / sfit0$dispersion,
             scale = exp(coef(fit0)) * sfit0$dispersion),
      0.08, 0.22, add = TRUE, col = "red") # fixed effect only
legend("right", title = "Probability mean less than", legend = " 0.1 is 0.0066115")
dev.off()
```


```{r}
set.seed(1)
library(lme4)
pdf(file = "Men_Density_Both.pdf")
fit2 <- glmer(RxnTime ~ (1 | Year) + (1 | Batch), data = men_pooled, family = Gamma(link = "log"))
fit0 <- glm(RxnTime ~ 1, data = men_pooled, family = Gamma(link = "log"))
sfit0 <- summary(fit0)
simfit <- function(fit2, n = 12000000) {
  vc <- as.data.frame(VarCorr(fit2))
  ## mu <- exp(coef(fit2)$Year[,]) ## using fitted random effects only
  z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
  mu <- exp(fixef(fit2) + z)
  shape <- 1 / vc$vcov[2]
  x <- rgamma(n, shape = shape, scale = mu / shape)
  x
}

x <- simfit(fit2)
mean(x < 0.1)
quantile(x, prob = c(.00001, .0001, .0005, .001))
## compare with and without random effect
plot(density(x), main = "Men's Pooled With Year and Batch Effect") # with random effect
curve(dgamma(x, shape = 1 / sfit0$dispersion,
             scale = exp(coef(fit0)) * sfit0$dispersion),
      0.08, 0.22, add = TRUE, col = "orange") # fixed effect only
legend("right", title = "Probability mean less than", legend = " 0.1 is 0")
dev.off()
```
```{r}
set.seed(1)
library(lme4)
pdf(file = "Women_Density_Year.pdf")
fit2 <- glmer(RxnTime ~ (1 | Year), data = women_pooled, family = Gamma(link = "log"))
fit0 <- glm(RxnTime ~ 1, data = women_pooled, family = Gamma(link = "log"))
sfit0 <- summary(fit0)
simfit <- function(fit2, n = 12000000) {
  vc <- as.data.frame(VarCorr(fit2))
  ## mu <- exp(coef(fit2)$Year[,]) ## using fitted random effects only
  z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
  mu <- exp(fixef(fit2) + z)
  shape <- 1 / vc$vcov[2]
  x <- rgamma(n, shape = shape, scale = mu / shape)
  x
}

x <- simfit(fit2)
mean(x < 0.1)
quantile(x, prob = c(.00001, .0001, .0005, .001))
## compare with and without random effect
plot(density(x), main = "Women's Pooled With Only Year Effect") # with random effect
curve(dgamma(x, shape = 1 / sfit0$dispersion,
             scale = exp(coef(fit0)) * sfit0$dispersion),
      0.08, 0.22, add = TRUE, col = "deeppink") # fixed effect only
legend("right", title = "Probability mean less than", legend = " 0.1 is 0.0042296")
dev.off()
```
```{r}
year_effect <- glmer(RxnTime ~ (1 | Year), data = men_pooled, family = Gamma(link = "log"))
batch_effect <- glmer(RxnTime ~ (1 | Batch), data = men_pooled, family = Gamma(link = "log"))
both <- glmer(RxnTime ~ (1 | Year) + (1 | Batch), data = men_pooled, family = Gamma(link = "log"))
#anova(batch_effect, both)
summary(both)
```


```{r}
t.test(men_pooled$RxnTime[men_pooled$Year==2019],men_pooled$RxnTime[men_pooled$Year==2022])
```


